### ISSUE TITLE
using stretchableImage for the button

### ISSUE THREAD

**Issue by Piero87** [takashisite/TSPopover#5]
Hello, i want know if i can use this image for the button in the TSActionSheet:

http://img259.imageshack.us/img259/548/alertredbutton2x.png

**Comment by takashisite** [comment]
Hi,
I have no plan to implement custom button image support at this time.

Check this article http://stackoverflow.com/questions/1427818/iphone-sdk-creating-a-big-red-uibutton .
Then modify TSActionSheet.m/buildButtons method.
I think add to new method (like cancelButtonWithTitle:Image)  is better.

**Comment by Piero87** [comment]
ok thanks!
